const { heroui } = require("@heroui/theme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    // packages/ui 컴포넌트 포함
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
    // HeroUI 테마 파일 포함
    "../../node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // 동적 배경색 클래스들
    "bg-red-100",
    "bg-red-200",
    "bg-red-300",
    "bg-orange-100",
    "bg-orange-200",
    "bg-orange-300",
    "bg-amber-100",
    "bg-amber-200",
    "bg-amber-300",
    "bg-yellow-100",
    "bg-yellow-200",
    "bg-yellow-300",
    "bg-lime-100",
    "bg-lime-200",
    "bg-lime-300",
    "bg-green-100",
    "bg-green-200",
    "bg-green-300",
    "bg-emerald-100",
    "bg-emerald-200",
    "bg-emerald-300",
    "bg-teal-100",
    "bg-teal-200",
    "bg-teal-300",
    "bg-cyan-100",
    "bg-cyan-200",
    "bg-cyan-300",
    "bg-sky-100",
    "bg-sky-200",
    "bg-sky-300",
    "bg-blue-100",
    "bg-blue-200",
    "bg-blue-300",
    "bg-indigo-100",
    "bg-indigo-200",
    "bg-indigo-300",
    "bg-violet-100",
    "bg-violet-200",
    "bg-violet-300",
    "bg-purple-100",
    "bg-purple-200",
    "bg-purple-300",
    "bg-fuchsia-100",
    "bg-fuchsia-200",
    "bg-fuchsia-300",
    "bg-pink-100",
    "bg-pink-200",
    "bg-pink-300",
    "bg-rose-100",
    "bg-rose-200",
    "bg-rose-300",
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [heroui()],
};
